services:
  #app_project:
  # image: 'learning-project'
  #  build: .
  #  volumes:
  #    - ./src/main/resources/db/changelogs:/liquibase-changelog.yml
  #  ports:
  #    - "8080:8080"
  postgres_db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres_db'
      - 'POSTGRES_PASSWORD=andrepassword'
      - 'POSTGRES_USER=andre'
    ports:
      - '5433:5432'
# 5433 -> map to my container locally / :5432 -> run container of PostgresSQL