services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_DB=project'
      - 'POSTGRES_PASSWORD=andrepassword'
      - 'POSTGRES_USER=andre'
    ports:
      - '5433:5432'
# 5433 -> map to my container locally / :5432 -> run container of PostgresSQL
