spring:
  jdbc:
    template:
      fetch-size: 100
  transaction:
    default-timeout: 500

  liquibase:
    change-log: classpath:db/changelogs/liquibase-changelog.yml

  rabbitmq:
    username: andre.chaves
    password: password