spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres_db
    username: andre
    password: andrepassword
  liquibase:
    changeLog: classpath:/db/changelogs/liquibase-changelog.yml
  jdbc:
    template:
      fetch-size: 100
  transaction:
    default-timeout: 500